### ISSUE TITLE
Preprocessing the Dataset

### ISSUE THREAD

**Issue by tamanna-sb** [tamanna037/InformationTypesDetectionNLP#5]
Since the dataset consists of text and it contains lots of code, user name, version number , URL and many more insignificant portions to identify the information type.

**Target**
1. Remove duplicate data
2. Clean Text like trimming

**Comment by tamanna-sb** [comment]
I have observed Bert does well even with having name or url. so no need to do 1 and 2

**Comment by minaoar** [comment]
Could you please elaborate the removal of emoticons? When I checked the dataset, it contains only ascii characters for some emoticons such as :) (found 42 instances). Do you want to remove all such smileys? Usually, some twitters have unicode emojis which are visual such as 😎. To remove the visual emojis libraries such as [demoji](https://pypi.org/project/demoji/) could be used. However, it seems that the dataset already contains the ascii characters.

**Comment by tamanna-sb** [comment]
I think these ascii characters can help to detect social conversation type. So for now, no need to remove those. What we have till now should be enough.
