### ISSUE TITLE
Use of Huggingface transformer

### ISSUE THREAD

**Issue by tamanna-sb** [tamanna037/InformationTypesDetectionNLP#8]
Since using simpletransforer, the model is not giving good results. I am thinking of trying hugging face transformer .

**Comment by minaoar** [comment]
HuggingFace provides great deep learning libraries and pre-trained models. However, if you plan to move the project to standalone machine, can you utilize GPU intensive libraries of HuggingFace? In that case the only other option will be to run this project in UCalgary ARC or TALC clusters. I think you can clarify this target deployment with Dr. Barcomb before moving to any such GPU or CPU direction.

**Comment by tamanna-sb** [comment]
Thanks for your suggestion. I will first check by myself ; if I could not do it, I will definitely contact Dr. Barcomb

**Comment by tamanna-sb** [comment]
Huggingface has been used for training in InfoTypesDetectionOss.py file ( [10](https://github.com/tamanna037/InformationTypesDetectionNLP/pull/10) )
